inherit_gem:
  tastyworks-development_dependencies: lib/tastyworks/rubocop.yml

Style/ClassAndModuleChildren:
  Enabled: false
Metrics/ClassLength:
  Max: 160
Metrics/ParameterLists:
  Max: 10
Style/AsciiComments:
  Enabled: false